- src/pages/index.tsx
> **openSUSE** is the only correct way to spell openSUSE.
> [https://en.opensuse.org/Help:Style#openSUSE_spelling](https://en.opensuse.org/Help:Style#openSUSE_spelling)
> contents(opensuse): normalize the spelling

- .github/workflows/autocorrect.yml
- contents/influxdata.mdx
InfluxData's GPG key got rotated recently, see <https://www.influxdata.com/blog/linux-package-signing-key-rotation/>. And the filename has changed to `influxdata-archive_compat.key`.
Also, the help docs for CentOS / RedHat in influxdata.mdx:
- They don't correctly spell "CentOS" and "RedHat".
- They use mirrored GPG key in configuration, which is considered not secure.
> Fix influxdata GPG key URL and filename (and typo fix)

- contents/epel.mdx
> Fix Link URL in EPEL Doc

- contents/debian-security.mdx
non-free-firmware only for bookworm/testing/sid in debian security
> non-free-firmware only for bookworm/testing/sid in debian security

- contents/nixpkgs.git.mdx
- src/routes.json
added basic usage for `nixpkgs.git` so users won't be confused by a 404 page at https://mirrors.tuna.tsinghua.edu.cn/help/nixpkgs.git/
> contents(nixpkgs.git): add nixpkgs.git help

- contents/nix-channels.mdx
Add code to demonstrate how to prevent the automatic appending of the default cache site, which can be especial helpful for users who are completely unable to reach the site.
See: https://github.com/tuna/mirror-web/pull/368
> contents(NixChannel): prevent auto appending

- contents/debian.mdx
Move Debian 12 to the first position to make it the default selection for the latest stable version (Debian 12)
> Update debian.mdx to select Debian 12 by default

- contents/homebrew.mdx
* Support for homebrew-cask-drivers repo has been removed since brew version 4.0.22, therefore any command-line settings related to that repo will report an error and thus should be removed.
* Error log: `Error: homebrew/cask-drivers was deprecated. This tap is now empty and all its contents were either deleted or migrated.`
* Ref: Homebrew/brew#15535
* Pinned warnings about mirror site changes
* Separated codeblocks that were co-used by Homebrew and Linuxbrew
The original PR was created at tuna/mirror-web#377 that also contained changes regarding homebrew-services repo. However, considering few mirror sites has supported that repo, those changes are not included in this PR. Discuss if needed.
> contents(homebrew): general updates

- contents/docker-ce.mdx
依照 docker 官方文档做出修改
+ debian/ubuntu 部分添加 raspbian 的帮助
+ 把 fedora 部分独立出来
+ centos/rhel 部分中把 centos 和 rhel 分开
> Ref:  https://docs.docker.com/engine/install/debian/
> https://docs.docker.com/engine/install/raspbian/
> https://docs.docker.com/engine/install/fedora/
> 依照上游修改 docker-ce 的帮助文档

- contents/crates.io-index.git.mdx
- contents/crates.io-index.mdx
Ref : [https://github.com/ustclug/mirrorhelp/pull/230](https://github.com/ustclug/mirrorhelp/pull/230)
> fix(crates.io-index): config file path error when install rust without default CARGO_HOME environment variable

- contents/CRAN.mdx
Ported from https://github.com/mirrorz-org/mirrorz-docs/pull/3
`apt-key` is deprecated, updating to `gpg`
> CRAN: follow upstream doc for key verification

- contents/ubuntu-ports.mdx
- contents/ubuntu.mdx
添加 Ubuntu 24.04 LTS 至 ubuntu 和 ubuntu-ports
> 同步 Ubuntu 生命周期

- contents/kubernetes.mdx
(Breaking change)
依赖于镜像站从 rsync://rsync.opensuse.org/buildservice-repos-main/isv:/kubernetes:/ 同步。
> contents(kubernetes): update docs to match latest repo

- contents/rpmfusion.mdx
- Put RHEL 8/9 before 7/6
- Remove instruction of using su -c 'CMD'
- Add sed command
- Make it clear that it only has Fedora example
- 请参考 -> 可参考
> contents(rpmfusion): add sed command and some other fixes

- contents/nix-channels.mdx
All other `nixos-rebuild` command on this page use (I believe) the correct `--option` except this one.
passing `--options` to `nix` command here on my system will result in
> error: unrecognised flag '--options'
I have only macOS at the moment, so this is just a guess and you should test it before accepting this change.
> Fix wrong option (and I believe a typo) for nixos-rebuild

- .gitignore
- .prettierrc
- contents/ghcup.mdx
- contents/hackage.mdx
fix #157
- 添加对于 stack >= v2.9.3 的配置方法
- 对于 GHCup 中 USTC 镜像连接进行修改
USTC 镜像对于 GHCup 的同步方式与 NJU 和 STJUG 镜像都不同，不应该使用相同的替换方式，所以使用原链接替代
>  Modify Hackage and GHCup contents

- contents/crates.io-index.git.mdx
- contents/crates.io-index.mdx
Cargo now recommends using configuration files with the `.toml` extension (see: [The Cargo Book](https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure)). The changes should be introduced to the help documentation.
> contents(crates): prefer `config.toml` format

- contents/fedora.mdx
This PR is related to #175 
- Fedora 38 and older versions are no longer officially supported (End of Life). The related content has been updated accordingly
- For Fedora 39 and newer versions, you only need to modify `fedora.repo` and `fedora-updates.repo` files to change mirrors. The automatic mirror-changing commands have been updated
- The manual mirror configuration files have been updated according to the latest release
> contents(fedora): Modify fedora help content

- contents/FreeBSD-pkg.mdx
[Poudriere](https://github.com/freebsd/poudriere) 是 FreeBSD 官方的构建系统，可以用来批量构建 `ports` 中的软件。
对于指定的包，例如`rust` `node-*` `llvm` 这种用户自编译带来性能提升不大的软件，Poudriere 可以使用`PACKAGE_FETCH_*` 来获取二进制包。
我增加了配置 Poudriere 让其使用镜像站的方法。
> contents(FreeBSD): Add usage information for poudriere build system

- contents/docker-ce.mdx
Fedora 41 根据 MirrorZ 文档操作报错，查询官方文档发现 Fedora 需要使用 `dnf-3`
```bash
[root@master ~]# dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
Unknown argument "--add-repo" for command "config-manager". Add "--help" for more information about the arguments.
[root@master ~]# dnf-3 config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
Adding repo from: https://download.docker.com/linux/fedora/docker-ce.repo
[root@master ~]# cat /etc/yum.repos.d/docker-ce.repo
[docker-ce-stable]
name=Docker CE Stable - $basearch
baseurl=https://download.docker.com/linux/fedora/$releasever/$basearch/stable
enabled=1
......
```
See https://docs.docker.com/engine/install/fedora/
> contents(docker-ce): fedora: sync with official doc

- contents/nix-channels.mdx
Some nix-channels mirrors cannot provide the entirety of cache.nixos.org, so we include it as fallback to avoid excessive rebuilds
> contents(nix-channels): Include cache.nixos.org in command line

- contents/rustup.mdx
基于以下观察：
1. 大多数发行版习惯于在 .profile 里 source .bashrc （https://github.com/mirrorz-org/mirrorz-help/issues/139#issuecomment-1951316017 ）
2. Debian 等发行版更倾向于使用 .profile 而非 .bash_profile，创建 .bash_profile 会破坏发行版原有设计 （https://github.com/mirrorz-org/mirrorz-help/issues/139#issuecomment-3036813776 ）
注：rustup-init 在安装 rust 时若勾选了设置环境变量，会同时写 .profile 和 .bashrc，内容都是 `. "$HOME/.cargo/env"`
该 PR 并不关闭 #139，因为 homebrew 等镜像的帮助文档依然存在写入  .bash_profile 的问题，需再针对 macOS 进行分析
> contents(rustup): Modify env definitions to .bashrc file
