mirrorz-org/mirrorz-help

- package-lock.json
- package.json
- src/components/layout/index.tsx
- src/components/page-meta/index.tsx
- src/lib/server/get-last-updated-timestamp.ts
- src/lib/server/parse-markdown.ts
- src/pages/[...content].tsx
Note: The feature has been fully implemented but only enabled in local development. We should only enable this in production when we migrate to GitHub Action (where the full clone is possible).
> feat(meta): show last updated

- shell.nix
Only for people who are too lazy to use a node.js version manager.
> Add a naive shell.nix

- contents/opensuse.mdx
Ref: https://github.com/ustclug/mirrorhelp/commit/7277e42088db2249860c72857a741b3e98e89b5c
> opensuse: ustc repo now contains backports contents

- contents/pypi.mdx
> contents(pypi): hack for PKU /simple url

- contents/eclipse.mdx
- contents/kodi.mdx
- contents/nodejs-release.mdx
- src/components/mdx-components/codeblock/highlight.tsx
- src/routes.json
Except NPM, Dockerhub, homebrew git repos and github-releases
> Merge USTC, almost

- contents/crates.io-index.git.mdx
- contents/crates.io-index.mdx
- src/routes.json
Ref to https://github.com/tuna/mirror-web/commit/70fe609d215204aa7639e475cb6ba7ee187a8bbe Ref to https://github.com/ustclug/mirrorhelp/commit/c3b67ee09292df9a6924ae6f126c6e7eef5b8857
> contents: add crates.io-index

- contents/aosp-monthly.mdx
- contents/homebrew.mdx
Ref to https://github.com/tuna/mirror-web/commit/5c1dea8231d140925c011f5f3725d593cbb49925
Ref to https://github.com/tuna/issues/issues/1668
> contents(homebrew): API env

- contents/influxdata.mdx
Ref to https://github.com/ustclug/mirrorhelp/commit/f8490bcde30ccf157ccdefbd954ccc25f5191b16 Ref to https://github.com/tuna/mirror-web/commit/0d7031e42fa5ee779193b85b26517a98e2f9ef0b
> contents(influxdata): update tuna and merge ustc

- contents/docker-ce.mdx
Ref to https://github.com/tuna/issues/issues/1707
See https://docs.docker.com/engine/install/debian/
> contents(docker-ce): mkdir keyring

- .github/ISSUE_TEMPLATE/1-content_feedback.yaml
- .github/ISSUE_TEMPLATE/2-bug_report.yaml
- .github/ISSUE_TEMPLATE/3-help_request.yaml
- .github/ISSUE_TEMPLATE/4-feature_request.yaml
- .github/ISSUE_TEMPLATE/config.yml
Related to https://github.com/mirrorz-org/mirrorz-help/issues/77
> chore: add github issue template

- src/components/layout/footer/index.tsx
- src/components/page-meta/index.tsx
- src/contexts/current-selected-mirror.tsx
- src/lib/client/constant.ts
- src/pages/404.tsx
- src/pages/500.tsx
Closes https://github.com/mirrorz-org/mirrorz-help/issues/77
> feat: add issue url

- contents/debian-security.mdx
- contents/debian.mdx
Moved to debian-archive
See https://github.com/tuna/issues/issues/1715
> contents(debian): remove jessie

- contents/debian-security.mdx
- contents/debian.mdx
To move to debian-archive
See https://lists.debian.org/debian-devel-announce/2023/03/msg00006.html
> contents(debian): remove stretch

- contents/docker-ce.mdx
> docker-ce: Improve debian documents

- contents/bioconductor.mdx
BioConductor documentation has been updated.  
An instruction has been added to help user use BioConductor mirror in an offline environment.  
Previous discussion:  
https://github.com/ZJUSCT/mirror-issues/issues/16
https://github.com/ZJUSCT/mirror-front/pull/60
> contents(BioConductor): merge zju

- contents/immortalwrt.mdx
- src/routes.json
Add OPKG setup instructions for the ImmortalWrt project.
> contents: add immortalwrt

- contents/alpine.mdx
> contents(alpine): fix sed

- contents/kubernetes.mdx
> 修复kubernetes gpg错误

- contents/nodejs-release.mdx
修正Node镜像文档的Volta配置，使其兼容Windows
Fix #123
> Fix nodejs-release volta config

- contents/debian-elts.mdx
- src/routes.json
Backport from https://github.com/mirrorz-org/mirrorz-docs/commit/130cbee695f4681704fbbf1baa16a007f8a13b31.
> contents(debian-elts): add debian-elts

- contents/winget-source.mdx
- src/routes.json
> contents(winget-source): Add

- contents/loongarch.mdx
- src/routes.json
> contents(loongarch): Add

- contents/fdroid.mdx
This adds instructions for how to get the _F-Droid.apk_ for first time installers.
> contents(fdroid): add first time install instructions

- contents/anthon.mdx
- src/routes.json
Fixed AOSC OS repository's help page
> contents(anthon): Modify AOSC OS repo help

- src/components/mdx-components/enhanced-codeblock/build-code.ts
- src/components/mdx-components/enhanced-codeblock/index.tsx
> feat: use echo | tee for quick setup

- contents/nodejs-release.mdx
为 nodejs-release 部分添加了 mise 相关内容
> contents(nodejs-release): add manual for mise

- contents/guix.git.mdx
- contents/guix.mdx
- src/components/mdx-components/codeblock/highlight.tsx
- src/routes.json
* add scheme highlight for guix configuration
> contents: add guix, guix.git

- contents/opam-repository.git.mdx
- src/routes.json
* OPAM may require opam-cache to figure out the correct configuration.
> contents: add opam-repository.git

- .autocorrectrc
- .github/workflows/autocorrect.yml
port of https://github.com/mirrorz-org/mirrorz-docs/pull/27
> chore(ci): fetch autocorrect using single-user Nix

- contents/CRAN.mdx
- contents/chef.mdx
- contents/elrepo.mdx
- contents/erlang-solutions.mdx
- contents/gitlab-ce.mdx
- contents/gitlab-runner.mdx
- contents/llvm-apt.mdx
- contents/mongodb.mdx
- contents/mysql.mdx
- contents/ros2.mdx
- contents/rudder.mdx
- contents/ubuntu-ports.mdx
- contents/ubuntu.mdx
- contents/virtualbox.mdx
- contents/wine-builds.mdx
...And update some software versions
> Remove focal (and older) from ubuntu releases, add EL9/10
